In [1]:
import numpy as np
import pandas as pd

In [33]:
df = pd.read_csv('data/car_evaluation.csv', header=None)

In [34]:
df.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [4]:
df.columns = [
    "buying",
    "maint",
    "doors",
    "persons",
    "lug_boot",
    "safety",
    "class"
]

In [5]:
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [6]:
for col in df.columns:
    print(df[col].value_counts())
    print('--------------------')

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
--------------------
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
--------------------
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64
--------------------
persons
2       576
4       576
more    576
Name: count, dtype: int64
--------------------
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64
--------------------
safety
low     576
med     576
high    576
Name: count, dtype: int64
--------------------
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64
--------------------

In [7]:
X = df.drop('class', axis=1)
y = df['class']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
encoder = OrdinalEncoder(
    categories=[
        ['low', 'med', 'high', 'vhigh'],
        ['low', 'med', 'high', 'vhigh'],
        ['2', '3', '4', '5more'],
        ['2', '4', 'more'],
        ['small', 'med', 'big'],
        ['low', 'med', 'high']
    ]
)

In [12]:
encoder.fit(X_train)

OrdinalEncoder(categories=[['low', 'med', 'high', 'vhigh'],
                           ['low', 'med', 'high', 'vhigh'],
                           ['2', '3', '4', '5more'], ['2', '4', 'more'],
                           ['small', 'med', 'big'], ['low', 'med', 'high']])

In [13]:
encoder.categories_

[array(['low', 'med', 'high', 'vhigh'], dtype=object),
 array(['low', 'med', 'high', 'vhigh'], dtype=object),
 array(['2', '3', '4', '5more'], dtype=object),
 array(['2', '4', 'more'], dtype=object),
 array(['small', 'med', 'big'], dtype=object),
 array(['low', 'med', 'high'], dtype=object)]

In [14]:
X_train = encoder.transform(X_train)

In [15]:
X_train

array([[3., 3., 3., 2., 2., 2.],
       [1., 3., 1., 1., 0., 1.],
       [0., 0., 3., 0., 2., 2.],
       ...,
       [2., 0., 3., 2., 1., 2.],
       [0., 2., 2., 0., 0., 1.],
       [1., 1., 1., 2., 0., 1.]])

In [16]:
X_test = encoder.transform(X_test)

In [17]:
y_train.value_counts()

class
unacc    975
acc      301
good      58
vgood     48
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()

In [20]:
y_train = le.fit_transform(y_train)

In [21]:
y_test = le.transform(y_test)

In [22]:
from sklearn.naive_bayes import CategoricalNB

In [23]:
model = CategoricalNB()

In [24]:
model.fit(X_train, y_train)

CategoricalNB()

In [25]:
y_pred = model.predict(X_test)

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.63      0.54      0.58        83
           1       0.57      0.36      0.44        11
           2       0.87      0.97      0.91       235
           3       1.00      0.35      0.52        17

    accuracy                           0.82       346
   macro avg       0.77      0.56      0.62       346
weighted avg       0.81      0.82      0.80       346

In [28]:
model.classes_

array([0, 1, 2, 3])

In [29]:
model.predict_proba(X_test)[0]

array([7.27318840e-03, 1.79323196e-05, 9.92054483e-01, 6.54396144e-04])

In [30]:
model.predict_log_proba(X_test)[0]

array([-4.92356051e+00, -1.09289059e+01, -7.97725069e-03, -7.33179766e+00])

In [31]:
model.class_count_

array([301.,  58., 975.,  48.])

In [32]:
model.n_categories_

array([4, 4, 4, 3, 3, 3])