In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [34]:
df = sns.load_dataset("mpg")

In [35]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [36]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [37]:
df = df.dropna()

In [38]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [39]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [50]:
X = df.drop(['mpg', 'name'], axis=1)
y = df["mpg"]

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [58]:
from sklearn.preprocessing import OneHotEncoder

In [59]:
ohe = OneHotEncoder(sparse_output=False, drop='first')

In [60]:
ohe.fit(X_train[['origin']])

OneHotEncoder(drop='first', sparse_output=False)

In [62]:
X_train[ohe.get_feature_names_out()] = ohe.transform(X_train[['origin']])

In [63]:
X_train = X_train.drop('origin', axis=1)

In [64]:
X_train.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
260,6,225.0,110.0,3620,18.7,78,0.0,1.0
184,4,140.0,92.0,2572,14.9,76,0.0,1.0
174,6,171.0,97.0,2984,14.5,75,0.0,1.0
64,8,318.0,150.0,4135,13.5,72,0.0,1.0
344,4,86.0,64.0,1875,16.4,81,0.0,1.0

In [65]:
X_test[ohe.get_feature_names_out()] = ohe.transform(X_test[['origin']])

In [66]:
X_test = X_test.drop('origin', axis=1)

In [67]:
X_test.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
79,4,96.0,69.0,2189,18.0,72,0.0,0.0
276,4,121.0,115.0,2795,15.7,78,0.0,0.0
248,4,91.0,60.0,1800,16.4,78,1.0,0.0
56,4,91.0,70.0,1955,20.5,71,0.0,1.0
393,4,140.0,86.0,2790,15.6,82,0.0,1.0

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
scaler = StandardScaler()

In [70]:
X_train = scaler.fit_transform(X_train)

In [71]:
X_test = scaler.transform(X_test)

In [72]:
from sklearn.neighbors import KNeighborsRegressor

In [73]:
knn = KNeighborsRegressor(n_neighbors=5)

In [74]:
knn.fit(X_train, y_train)

KNeighborsRegressor()

In [75]:
y_pred = knn.predict(X_test)

In [76]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [81]:
mean_absolute_error(y_test, y_pred)

2.0455696202531644

In [78]:
mean_squared_error(y_test, y_pred)

7.41826835443038

In [79]:
np.sqrt(mean_squared_error(y_test, y_pred))

np.float64(2.7236498222844983)

In [80]:
r2_score(y_test, y_pred)

0.8546594124998885

In [86]:
for k in range(1, 11):
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    print(k, r2_score(y_test, y_pred))

1 0.8266209645955658
2 0.8319579934067565
3 0.8568938882426853
4 0.8586897930642484
5 0.8546594124998885
6 0.8568820392010248
7 0.8504762909417242
8 0.841324609172075
9 0.8358717900408201
10 0.8275182897649268

In [87]:
for k in range(1, 11):
    knn = KNeighborsRegressor(n_neighbors=k, weights='distance')
    knn.fit(X_train, y_train)

    accuracy = knn.score(X_test, y_test)

    print(k, accuracy)

1 0.8266209645955658
2 0.8377182745745937
3 0.8597831877627902
4 0.8663279430933459
5 0.8678694151368082
6 0.8722929895356366
7 0.8698039643800418
8 0.8642914082894602
9 0.8600396133151331
10 0.8545343259904785