In [1]:
import pandas as pd

In [11]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red'],
    'Size': ['small', 'large', 'large', 'large']
})

In [7]:
df

   Color   Size
0    Red  small
1   Blue  large
2  Green  large
3    Red  large

In [4]:
df['Color'].value_counts()

Color
Red      2
Blue     1
Green    1
Name: count, dtype: int64

In [10]:
pd.get_dummies(df)

   Score  Color_Blue  Color_Green  Color_Red  Size_large  Size_small
0      1       False        False       True       False        True
1      3        True        False      False        True       False
2      4       False         True      False        True       False
3      6       False        False       True        True       False

In [14]:
pd.get_dummies(df, columns=['Color'])

    Size  Color_Blue  Color_Green  Color_Red
0  small       False        False       True
1  large        True        False      False
2  large       False         True      False
3  large       False        False       True

In [15]:
pd.get_dummies(df, columns=['Color'], drop_first=True)

    Size  Color_Green  Color_Red
0  small        False       True
1  large        False      False
2  large         True      False
3  large        False       True