In [49]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [33]:
df = sns.load_dataset('titanic')

In [34]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [35]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [36]:
df['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [37]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [39]:
df.shape

(891, 15)

In [40]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [41]:
df = df.drop(['deck', 'embark_town', 'alive', 'class', 'who', 'adult_male'], axis=1)

In [42]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0           0       3    male  22.0      1      0   7.2500        S  False
1           1       1  female  38.0      1      0  71.2833        C  False
2           1       3  female  26.0      0      0   7.9250        S   True
3           1       1  female  35.0      1      0  53.1000        S  False
4           0       3    male  35.0      0      0   8.0500        S   True
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
886         0       2    male  27.0      0      0  13.0000        S   True
887         1       1  female  19.0      0      0  30.0000        S   True
888         0       3  female   NaN      1      2  23.4500        S  False
889         1       1    male  26.0      0      0  30.0000        C   True
890         0       3    male  32.0      0      0   7.7500        Q   True

[891 rows x 9 columns]

In [43]:
df['age'] = df['age'].fillna(df['age'].mean())

In [44]:
df = df.dropna(subset='embarked')

In [45]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [46]:
df['alone'] = df['alone'].astype(int)

In [47]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.000000,1,0,7.2500,S,0
1,1,1,female,38.000000,1,0,71.2833,C,0
2,1,3,female,26.000000,0,0,7.9250,S,1
3,1,1,female,35.000000,1,0,53.1000,S,0
4,0,3,male,35.000000,0,0,8.0500,S,1
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,1
887,1,1,female,19.000000,0,0,30.0000,S,1
888,0,3,female,29.699118,1,2,23.4500,S,0
889,1,1,male,26.000000,0,0,30.0000,C,1
890,0,3,male,32.000000,0,0,7.7500,Q,1

In [64]:
X = df.drop('survived', axis=1)

In [51]:
y = df['survived']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [65]:
ohe = OneHotEncoder(sparse_output=False, drop='first')

In [66]:
X_train

     pclass     sex        age  sibsp  parch      fare embarked  alone
708       1  female  22.000000      0      0  151.5500        S      1
240       3  female  29.699118      1      0   14.4542        C      0
382       3    male  32.000000      0      0    7.9250        S      1
792       3  female  29.699118      8      2   69.5500        S      0
683       3    male  14.000000      5      2   46.9000        S      0
..      ...     ...        ...    ...    ...       ...      ...    ...
107       3    male  29.699118      0      0    7.7750        S      1
271       3    male  25.000000      0      0    0.0000        S      1
862       1  female  48.000000      0      0   25.9292        S      1
436       3  female  21.000000      2      2   34.3750        S      0
103       3    male  33.000000      0      0    8.6542        S      1

[711 rows x 8 columns]

In [67]:
ohe.fit(X_train[['sex', 'embarked']])

OneHotEncoder(drop='first', sparse_output=False)

In [68]:
X_train[ohe.get_feature_names_out()] = ohe.transform(X_train[['sex', 'embarked']])

In [69]:
X_train

,pclass,sex,age,sibsp,parch,fare,embarked,alone,sex_male,embarked_Q,embarked_S
708,1,female,22.000000,0,0,151.5500,S,1,0.0,0.0,1.0
240,3,female,29.699118,1,0,14.4542,C,0,0.0,0.0,0.0
382,3,male,32.000000,0,0,7.9250,S,1,1.0,0.0,1.0
792,3,female,29.699118,8,2,69.5500,S,0,0.0,0.0,1.0
683,3,male,14.000000,5,2,46.9000,S,0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
107,3,male,29.699118,0,0,7.7750,S,1,1.0,0.0,1.0
271,3,male,25.000000,0,0,0.0000,S,1,1.0,0.0,1.0
862,1,female,48.000000,0,0,25.9292,S,1,0.0,0.0,1.0
436,3,female,21.000000,2,2,34.3750,S,0,0.0,0.0,1.0
103,3,male,33.000000,0,0,8.6542,S,1,1.0,0.0,1.0

In [70]:
X_train = X_train.drop(columns=['sex', 'embarked'])

In [71]:
X_train

,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
708,1,22.000000,0,0,151.5500,1,0.0,0.0,1.0
240,3,29.699118,1,0,14.4542,0,0.0,0.0,0.0
382,3,32.000000,0,0,7.9250,1,1.0,0.0,1.0
792,3,29.699118,8,2,69.5500,0,0.0,0.0,1.0
683,3,14.000000,5,2,46.9000,0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
107,3,29.699118,0,0,7.7750,1,1.0,0.0,1.0
271,3,25.000000,0,0,0.0000,1,1.0,0.0,1.0
862,1,48.000000,0,0,25.9292,1,0.0,0.0,1.0
436,3,21.000000,2,2,34.3750,0,0.0,0.0,1.0
103,3,33.000000,0,0,8.6542,1,1.0,0.0,1.0

In [72]:
y_train

708    1
240    0
382    0
792    0
683    0
      ..
107    1
271    1
862    1
436    0
103    0
Name: survived, Length: 711, dtype: int64